name: 'Plugin Check'
on:
  pull_request:
  push:
    branches:
    - trunk
    - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Remove .env files
      run: |
        rm .distignore
        rm .gitignore
    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1