name: Playwright Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17'

    - name: Install dependencies
      run: npm install

    - name: Run Playwright tests
      run: npm run test:playwright